### ISSUE TITLE
ModuleNotFoundError: No module named 'discord'

### ISSUE THREAD

**Issue by someoneidk12** [mccoderpy/discord.py-message-components#1]
I get the "ModuleNotFoundError: No module named 'discord'" error everytime i try to run my script. I did as you said, uninstall the original lib then install yours. Now vscode is throwing that error
![image_2021-06-08_154353](https://user-images.githubusercontent.com/85565526/121195999-64ebcf00-c870-11eb-9034-3ca92a21ed51.png)

**Comment by mccoderpy** [comment]
@someoneidk12 
yes, there was a problem with the installation because it installed it in a folder called `src`. Yust install version 1.0.2 that should fix it. (Yes the version sequence is strange I know I have to delete the other ones, but i nead my phone for that)

**Comment by someoneidk12** [comment]
That did it, Cheers!
