### ISSUE TITLE
Bug in emoji initialisation for SelectOption

### ISSUE THREAD

**Issue by IvanSteuerberg** [mccoderpy/discord.py-message-components#16]
In components.py line 275 the if should be elif (As in Button init -> components.py line 95)

**Comment by mccoderpy** [comment]
It is an elif [here](https://github.com/mccoderpy/discord.py-message-components/blob/ecf7ba6e2ed8b2a9b123d6f5694f92e87cd1574d/discord/components.py#L275). If you mean the PyPi version, as mentioned in this [discussion](#17)  it is full of bugs. It is better to use the developer branch.

**Comment by mccoderpy** [comment]
I'm closing this now because it is already solved.
