### ISSUE TITLE
Interaction.defer()

### ISSUE THREAD

**Issue by malikmajai** [mccoderpy/discord.py-message-components#21]
Hi, If I use inter.defer(), I am not able to send Modals. 

![image](https://user-images.githubusercontent.com/92770716/166161842-3af9729c-3ee1-4fbb-9581-575fd6375512.png)

![image](https://user-images.githubusercontent.com/92770716/166161845-d1ae2b5b-0a97-47bb-abfd-08c8f99b7fb3.png)

**Comment by mccoderpy** [comment]
So does this works now?
