### ISSUE TITLE
Slash Commands options can't be required = False

### ISSUE THREAD

**Issue by malikmajai** [mccoderpy/discord.py-message-components#22]
![image](https://user-images.githubusercontent.com/92770716/166186479-45d5cc29-2eea-4902-9f8c-4fd9815f8428.png)

![image](https://user-images.githubusercontent.com/92770716/166186416-0836f61f-efe0-4414-af18-036ba5de5c82.png)

**Comment by mccoderpy** [comment]
> 
> ![image](https://user-images.githubusercontent.com/92770716/166186479-45d5cc29-2eea-4902-9f8c-4fd9815f8428.png)
> 
> ![image](https://user-images.githubusercontent.com/92770716/166186416-0836f61f-efe0-4414-af18-036ba5de5c82.png)

yoz must set q default value

**Comment by malikmajai** [comment]
Thanks, didn't noticed.
