### ISSUE TITLE
[Feature Request]:

### ISSUE THREAD

**Issue by itsTooooooooom** [mccoderpy/discord.py-message-components#57]
### Summary

Cooldown for Commands etc.

### What is the feature request for?

The core library

### The Problem

I think it is self-explaining, but I am trying to make a cooldown for some commands. 😁 
I don’t know if it has been suggested yet, but yeah

### The Ideal Solution

Making a commands.Cooldown(…), like in it is used in discord.py

### Additional Context

Doesn't need to be in the library as fast as possible, but it would help me a lot, because it saves lot of time and code

**Comment by mccoderpy** [comment]
The commands framework of discord.py hasn't changed. You can still use its cooldowns like before

**Comment by itsTooooooooom** [comment]
Oh okay, thought you said thats its not integrated in the library yet. But thanks anyway!

**Comment by mccoderpy** [comment]
> Oh okay, thought you said thats its not integrated in the library yet. But thanks anyway!

That was about builtin support for app-command cooldowns, not cooldowns in general ^^

You're welcome

**Comment by mccoderpy** [comment]
Also please give the issue a name next time😀

**Comment by itsTooooooooom** [comment]
Oh yes, I forgot it 😅
